QT       += core gui printsupport concurrent svg

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# ---- Single-source version ---------------------------------------------------
# include/constants.h (AppVersion) is the authoritative version. Parse it here so
# the Qt VERSION and the Windows resource (.rc) never carry a duplicate literal.
# To bump the version, edit only AppVersion in include/constants.h.
VERSION_SOURCE = $$PWD/include/constants.h
VER_MAJOR =
VER_MINOR =
VER_PATCH =
# Match only the "kMajor = <n>" definition line; the toString() line also mentions
# kMajor/kMinor/kPatch (via .arg(...)) but has no "=" and must be ignored.
VER_LINES = $$cat($$VERSION_SOURCE, lines)
for(line, VER_LINES) {
    contains(line, ".*kMajor *=.*"): VER_MAJOR = $$replace(line, ".*kMajor[^0-9]*([0-9]+).*", "\\1")
    contains(line, ".*kMinor *=.*"): VER_MINOR = $$replace(line, ".*kMinor[^0-9]*([0-9]+).*", "\\1")
    contains(line, ".*kPatch *=.*"): VER_PATCH = $$replace(line, ".*kPatch[^0-9]*([0-9]+).*", "\\1")
}
if(isEmpty(VER_MAJOR)|isEmpty(VER_MINOR)|isEmpty(VER_PATCH)) {
    error("Could not parse AppVersion (kMajor/kMinor/kPatch) from $$VERSION_SOURCE")
}
VERSION = $${VER_MAJOR}.$${VER_MINOR}.$${VER_PATCH}

# Emit a numeric-only header consumed by the .rc so its FILEVERSION and version
# strings track constants.h automatically. Regenerated on every qmake run.
ver_rc_lines = \
    "// Auto-generated by qmake from include/constants.h - do not edit." \
    "$${LITERAL_HASH}define APP_VER_MAJOR $$VER_MAJOR" \
    "$${LITERAL_HASH}define APP_VER_MINOR $$VER_MINOR" \
    "$${LITERAL_HASH}define APP_VER_PATCH $$VER_PATCH"
write_file($$OUT_PWD/version_autogen.h, ver_rc_lines)
RC_INCLUDEPATH += $$OUT_PWD
# -----------------------------------------------------------------------------


# include/ subfolders are all on the path so existing flat #include "foo.h"
# directives keep resolving after the by-layer reorganization.
INCLUDEPATH += \
    $$PWD/include/ \
    $$PWD/include/dto/ \
    $$PWD/include/model/ \
    $$PWD/include/viewmodel/ \
    $$PWD/include/view/ \
    $$PWD/lib/irig106/include/

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

win32 {
    LIBS += -lws2_32 # Windows sockets, specifically WSASocketW()
    # user32: MainView::nativeEvent (frameless window) calls GetWindowRect /
    # ScreenToClient / IsZoomed / GetSystemMetrics, which live in user32.lib.
    LIBS += -luser32
}

# Compile the vendored third-party lib (lib/irig106) without the
# app's -Wall -Wextra so their pre-existing warnings don't bury real app warnings.
include($$PWD/thirdparty.pri)

# Application sources, grouped by MVVM layer.
SOURCES += src/main.cpp

# Model: data ingestion, processing pipeline, domain logic
SOURCES += \
    src/model/channeldata.cpp \
    src/model/chapter10reader.cpp \
    src/model/ch10packetreader.cpp \
    src/model/framesetup.cpp \
    src/model/frameprocessor.cpp \
    src/model/stepdetector.cpp \
    src/model/calibrationextractor.cpp \
    src/model/csvseriesparser.cpp \
    src/model/seriescolumnschema.cpp \
    src/model/streamconfigschema.cpp \
    src/model/processingtemplateschema.cpp \
    src/model/templatematcher.cpp \
    src/model/tomlconfighelper.cpp

# ViewModel: presentation state + processing orchestration
SOURCES += \
    src/viewmodel/mainviewmodel.cpp \
    src/viewmodel/processingcoordinator.cpp \
    src/viewmodel/plotviewmodel.cpp

# View: widgets and dialogs
SOURCES += \
    src/view/mainview.cpp \
    src/view/streamconfigdialog.cpp \
    src/view/streamsubdialogs.cpp \
    src/view/exportdialog.cpp \
    src/view/batchapplydialog.cpp \
    src/view/plotcustomizationdialog.cpp \
    src/view/processingprogressdialog.cpp \
    src/view/plotwidget.cpp \
    src/view/tmchart.cpp

# Third-party libraries
SOURCES += \
    lib/irig106/src/irig106ch10.c \
    lib/irig106/src/i106_time.c \
    lib/irig106/src/i106_data_stream.c \
    lib/irig106/src/i106_decode_time.c \
    lib/irig106/src/i106_decode_tmats.c \
    lib/irig106/src/i106_decode_tmats_g.c \
    lib/irig106/src/i106_decode_tmats_r.c \
    lib/irig106/src/i106_decode_tmats_m.c \
    lib/irig106/src/i106_decode_tmats_p.c \
    lib/irig106/src/i106_decode_tmats_b.c \
    lib/irig106/src/i106_decode_tmats_c.c \
    lib/irig106/src/i106_decode_tmats_d.c \
    lib/irig106/src/i106_decode_pcmf1.c \

# Application headers, grouped by MVVM layer.
# Shared / cross-cutting
HEADERS += \
    include/constants.h

# Model: data ingestion, processing pipeline, domain logic
HEADERS += \
    include/model/channeldata.h \
    include/model/chapter10reader.h \
    include/model/ch10packetreader.h \
    include/model/packetqueue.h \
    include/model/framesetup.h \
    include/model/frameprocessor.h \
    include/model/stepdetector.h \
    include/model/calibrationextractor.h \
    include/model/csvseriesparser.h \
    include/model/seriescolumnschema.h \
    include/model/streamconfigschema.h \
    include/model/processingtemplateschema.h \
    include/model/templatematcher.h \
    include/model/tomlconfighelper.h

# DTOs: plain data carried across layers
HEADERS += \
    include/dto/streamconfig.h \
    include/dto/framesyncparams.h \
    include/dto/processingparams.h \
    include/dto/processedstreamdata.h \
    include/dto/plotseriesdata.h \
    include/dto/calibrationprofile.h \
    include/dto/source.h \
    include/dto/seriesappearance.h \
    include/dto/processingtemplate.h

# ViewModel: presentation state + processing orchestration
HEADERS += \
    include/viewmodel/mainviewmodel.h \
    include/viewmodel/processingcoordinator.h \
    include/viewmodel/plotviewmodel.h

# View: widgets and dialogs
HEADERS += \
    include/view/mainview.h \
    include/view/streamconfigdialog.h \
    include/view/streamsubdialogs.h \
    include/view/exportdialog.h \
    include/view/batchapplydialog.h \
    include/view/plotcustomizationdialog.h \
    include/view/processingprogressdialog.h \
    include/view/plotwidget.h \
    include/view/tmchart.h

# Third-party libraries
HEADERS += \
    lib/irig106/include/irig106ch10.h \
    lib/irig106/include/i106_data_stream.h \
    lib/irig106/include/i106_decode_time.h \
    lib/irig106/include/i106_time.h \
    lib/irig106/include/i106_stdint.h \
    lib/irig106/include/config.h \
    lib/irig106/include/i106_decode_tmats.h \
    lib/irig106/include/i106_decode_tmats_g.h \
    lib/irig106/include/i106_decode_tmats_r.h \
    lib/irig106/include/i106_decode_tmats_m.h \
    lib/irig106/include/i106_decode_tmats_p.h \
    lib/irig106/include/i106_decode_tmats_b.h \
    lib/irig106/include/i106_decode_tmats_c.h \
    lib/irig106/include/i106_decode_tmats_d.h \
    lib/irig106/include/i106_decode_tmats_common.h \
    lib/irig106/include/i106_decode_pcmf1.h \

RESOURCES += \
    resources/win11-dark.qss \
    resources/win11-light.qss \
    resources/icon.ico \
    resources/checkmark.svg \
    resources/chevron-down-dark.svg \
    resources/chevron-down-light.svg \
    resources/chevron-right-dark.svg \
    resources/chevron-right-light.svg \
    resources/chevron-down-disabled-dark.svg \
    resources/chevron-down-disabled-light.svg \
    resources/folder-open.svg \
    resources/floppy-save.svg \
    resources/play.svg \
    resources/gear.svg \
    resources/retry.svg \
    resources/export-dark.svg \
    resources/export-light.svg \
    resources/import-dark.svg \
    resources/import-light.svg \
    resources/toggle-on-dark.svg \
    resources/toggle-off-dark.svg \
    resources/toggle-on-light.svg \
    resources/toggle-off-light.svg \
    resources/usermanual.html

RC_FILE = resources/tmDataQualityAnalyzer_resource.rc

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

TARGET = tmDataQualityAnalyzer
