QT       += core gui printsupport concurrent svg

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# ---- Single-source version ---------------------------------------------------
# include/constants.h (AppVersion) is the authoritative version. Parse it here so
# the Qt VERSION and the Windows resource (.rc) never carry a duplicate literal.
# To bump the version, edit only AppVersion in include/constants.h.
VERSION_SOURCE = $$PWD/include/constants.h
VER_MAJOR =
VER_MINOR =
VER_PATCH =
# Match only the "kMajor = <n>" definition line; the toString() line also mentions
# kMajor/kMinor/kPatch (via .arg(...)) but has no "=" and must be ignored.
VER_LINES = $$cat($$VERSION_SOURCE, lines)
for(line, VER_LINES) {
    contains(line, ".*kMajor *=.*"): VER_MAJOR = $$replace(line, ".*kMajor[^0-9]*([0-9]+).*", "\\1")
    contains(line, ".*kMinor *=.*"): VER_MINOR = $$replace(line, ".*kMinor[^0-9]*([0-9]+).*", "\\1")
    contains(line, ".*kPatch *=.*"): VER_PATCH = $$replace(line, ".*kPatch[^0-9]*([0-9]+).*", "\\1")
}
if(isEmpty(VER_MAJOR)|isEmpty(VER_MINOR)|isEmpty(VER_PATCH)) {
    error("Could not parse AppVersion (kMajor/kMinor/kPatch) from $$VERSION_SOURCE")
}
VERSION = $${VER_MAJOR}.$${VER_MINOR}.$${VER_PATCH}

# Emit a numeric-only header consumed by the .rc so its FILEVERSION and version
# strings track constants.h automatically. Regenerated on every qmake run.
ver_rc_lines = \
    "// Auto-generated by qmake from include/constants.h - do not edit." \
    "$${LITERAL_HASH}define APP_VER_MAJOR $$VER_MAJOR" \
    "$${LITERAL_HASH}define APP_VER_MINOR $$VER_MINOR" \
    "$${LITERAL_HASH}define APP_VER_PATCH $$VER_PATCH"
write_file($$OUT_PWD/version_autogen.h, ver_rc_lines)
RC_INCLUDEPATH += $$OUT_PWD
# -----------------------------------------------------------------------------


INCLUDEPATH += \
    $$PWD/include/ \
    $$PWD/lib/irig106/include/ \
    $$PWD/lib/qcustomplot/

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

win32 {
    LIBS += -lws2_32 # Need this for Windows 32-bit functions, specifically WSASocketW()
    QMAKE_CXXFLAGS += -Wa,-mbig-obj  # Required for QCustomPlot large object file on MinGW
}

SOURCES += \
    src/channeldata.cpp \
    src/chapter10reader.cpp \
    src/ch10packetreader.cpp \
    src/framesetup.cpp \
    src/main.cpp \
    src/mainviewmodel.cpp \
    src/processingcoordinator.cpp \
    src/mainview.cpp \
    src/streamconfigdialog.cpp \
    src/timeextractionwidget.cpp \
    src/exportdialog.cpp \
    src/frameprocessor.cpp \
    src/stepdetector.cpp \
    src/calibrationextractor.cpp \
    src/plotviewmodel.cpp \
    src/plotcustomizationdialog.cpp \
    src/plotwidget.cpp \
    src/tomlconfighelper.cpp \
    lib/irig106/src/irig106ch10.c \
    lib/irig106/src/i106_time.c \
    lib/irig106/src/i106_data_stream.c \
    lib/irig106/src/i106_decode_time.c \
    lib/irig106/src/i106_decode_tmats.c \
    lib/irig106/src/i106_decode_tmats_g.c \
    lib/irig106/src/i106_decode_tmats_r.c \
    lib/irig106/src/i106_decode_tmats_m.c \
    lib/irig106/src/i106_decode_tmats_p.c \
    lib/irig106/src/i106_decode_tmats_b.c \
    lib/irig106/src/i106_decode_tmats_c.c \
    lib/irig106/src/i106_decode_tmats_d.c \
    lib/irig106/src/i106_decode_pcmf1.c \
    lib/qcustomplot/qcustomplot.cpp

HEADERS += \
    include/channeldata.h \
    include/chapter10reader.h \
    include/ch10packetreader.h \
    include/constants.h \
    include/framesetup.h \
    include/calibrationprofile.h \
    include/stepdetector.h \
    include/calibrationextractor.h \
    include/packetqueue.h \
    include/mainviewmodel.h \
    include/processingcoordinator.h \
    include/mainview.h \
    include/streamconfig.h \
    include/streamconfigdialog.h \
    include/processedstreamdata.h \
    include/frameprocessor.h \
    include/processingparams.h \
    include/timefields.h \
    include/timeextractionwidget.h \
    include/exportdialog.h \
    include/plotviewmodel.h \
    include/plotcustomizationdialog.h \
    include/plotwidget.h \
    include/tomlconfighelper.h \
    lib/irig106/include/irig106ch10.h \
    lib/irig106/include/i106_data_stream.h \
    lib/irig106/include/i106_decode_time.h \
    lib/irig106/include/i106_time.h \
    lib/irig106/include/i106_stdint.h \
    lib/irig106/include/config.h \
    lib/irig106/include/i106_decode_tmats.h \
    lib/irig106/include/i106_decode_tmats_g.h \
    lib/irig106/include/i106_decode_tmats_r.h \
    lib/irig106/include/i106_decode_tmats_m.h \
    lib/irig106/include/i106_decode_tmats_p.h \
    lib/irig106/include/i106_decode_tmats_b.h \
    lib/irig106/include/i106_decode_tmats_c.h \
    lib/irig106/include/i106_decode_tmats_d.h \
    lib/irig106/include/i106_decode_tmats_common.h \
    lib/irig106/include/i106_decode_pcmf1.h \
    lib/qcustomplot/qcustomplot.h

RESOURCES += \
    resources/win11-dark.qss \
    resources/win11-light.qss \
    resources/icon.ico \
    resources/checkmark.svg \
    resources/chevron-down-dark.svg \
    resources/chevron-down-light.svg \
    resources/chevron-right-dark.svg \
    resources/chevron-right-light.svg \
    resources/chevron-down-disabled-dark.svg \
    resources/chevron-down-disabled-light.svg \
    resources/folder-open.svg \
    resources/floppy-save.svg \
    resources/play.svg \
    resources/stop.svg \
    resources/gear.svg \
    resources/retry.svg \
    resources/export.svg \
    resources/toggle-on-dark.svg \
    resources/toggle-off-dark.svg \
    resources/toggle-on-light.svg \
    resources/toggle-off-light.svg

RC_FILE = resources/tmDataQualityAnalyzer_resource.rc

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

TARGET = tmDataQualityAnalyzer
