/**
 * @file plotexport.cpp
 * @brief Exporting the plot as an image (US6.0).
 *
 * One rendering path serves screen, PNG, SVG and PDF - TmChart::renderTo() -
 * so the three formats cannot drift apart. That mattered: savePdf() used to be
 * a third path that rendered only the chart, silently dropping the legend that
 * PNG and SVG both composited in.
 *
 * exportImage() is the headless entry point; the batch loop's per-file export
 * calls it through the callback MainView hands to BatchController.
 */

#include "plotwidget.h"

#include <QCoreApplication>
#include <QFileDialog>
#include <QFileInfo>
#include <QPageSize>
#include <QPainter>
#include <QPdfWriter>
#include <QPixmap>
#include <QRegularExpression>
#include <QSettings>
#include <QtSvg/QSvgGenerator>

#include "constants.h"
#include "exportdialog.h"
#include "plotlegendoverlay.h"
#include "plotviewmodel.h"
#include "tmchart.h"

void PlotWidget::onExportPlot()
{
    if (m_view_model == nullptr || !m_view_model->hasData())
    {
        return;
    }

    QSettings settings;
    QString last_dir = settings.value(UIConstants::kSettingsKeyLastCh10Dir, QCoreApplication::applicationDirPath()).toString();

    QString default_name = m_view_model->plotTitle().isEmpty() ? "plot" : m_view_model->plotTitle();
    default_name.replace(QRegularExpression("[\\\\/:*?\"<>|]"), "_");
    QString base_path = QDir(last_dir).filePath(default_name);

    ExportDialog dialog(base_path + ".csv", base_path + ".png", base_path + "_log.txt", this);
    if (dialog.exec() == QDialog::Accepted)
    {
        if (dialog.exportCsv())
        {
            if (m_view_model->exportCsv(dialog.csvPath()))
            {
                emit logMessage(QString("<span style='color:green;'>Data exported to <a href='file:///%1'>%1</a></span>")
                                .arg(dialog.csvPath()));
            }
            else
            {
                emit logMessage(QString("<span style='color:red;'>Error: Failed to export data to %1</span>")
                                .arg(dialog.csvPath()));
            }
        }

        if (dialog.exportImage())
        {
            exportImage(dialog.imagePath());
        }

        if (dialog.exportLog())
        {
            const QString log_path = dialog.logPath();
            const QString log_text = m_log_text_provider ? m_log_text_provider() : QString();

            QFile file(log_path);
            if (file.open(QIODevice::WriteOnly | QIODevice::Text))
            {
                QTextStream stream(&file);
                stream << log_text;
                if (!log_text.endsWith('\n'))
                {
                    stream << '\n';
                }
                file.close();
                emit logMessage(QString("<span style='color:green;'>Log exported to <a href='file:///%1'>%1</a></span>")
                                .arg(log_path));
            }
            else
            {
                emit logMessage(QString("<span style='color:red;'>Error: Failed to export log to %1</span>")
                                .arg(log_path));
            }
        }
    }
}

bool PlotWidget::exportImage(const QString& path)
{
    if (m_view_model == nullptr)
    {
        return false;
    }

    QString filename = path;
    QString suffix = QFileInfo(filename).suffix().toLower();
    bool success = false;
    QString formatStr;

    if (suffix == "png")
    {
        // The legend floats over the chart as a child widget, so render it onto
        // the image at its on-screen position (WYSIWYG - if the legend is
        // scrolled, the exported view matches).
        QPixmap px(m_plot->size());
        px.fill(Qt::transparent);
        QPainter painter(&px);
        m_plot->renderTo(painter, m_plot->size());
        if (m_legend != nullptr && m_legend->isVisible())
        {
            m_legend->render(&painter, m_legend->pos());
        }
        painter.end();
        success = px.save(filename, "PNG");
        formatStr = "PNG";
    }
    else if (suffix == "svg")
    {
        QSvgGenerator generator;
        generator.setFileName(filename);
        generator.setSize(m_plot->size());
        generator.setViewBox(QRect(0, 0, m_plot->width(), m_plot->height()));
        generator.setTitle(m_view_model->plotTitle());
        generator.setDescription("Generated by tmDataQualityAnalyzer");

        QPainter painter;
        success = painter.begin(&generator);
        if (success)
        {
            m_plot->renderTo(painter, m_plot->size());
            if (m_legend != nullptr && m_legend->isVisible())
            {
                m_legend->render(&painter, m_legend->pos());
            }
            painter.end();
        }
        formatStr = "SVG";
    }
    else
    {
        // Default to PDF
        if (!filename.endsWith(".pdf", Qt::CaseInsensitive))
        {
            filename += ".pdf";
        }
        // The same renderTo() as PNG and SVG, so all three agree. The previous
        // PDF path rendered only the chart and silently dropped the legend.
        QPdfWriter writer(filename);
        writer.setPageSize(QPageSize(m_plot->size(), QPageSize::Point));
        writer.setPageMargins(QMarginsF(0, 0, 0, 0));
        QPainter painter;
        success = painter.begin(&writer);
        if (success)
        {
            // The PDF device has its own (much finer) resolution, so scale the
            // logical widget geometry onto the page rather than painting 1:1.
            const double sx = writer.width()  / static_cast<double>(m_plot->width());
            const double sy = writer.height() / static_cast<double>(m_plot->height());
            painter.scale(sx, sy);
            m_plot->renderTo(painter, m_plot->size());
            if (m_legend != nullptr && m_legend->isVisible())
            {
                m_legend->render(&painter, m_legend->pos());
            }
            painter.end();
        }
        formatStr = "PDF";
    }

    if (success)
    {
        emit logMessage(QString("<span style='color:green;'>Plot exported as %1 to <a href='file:///%2'>%2</a></span>")
                        .arg(formatStr)
                        .arg(filename));
    }
    else
    {
        emit logMessage(QString("<span style='color:red;'>Error: Failed to export plot to %1</span>")
                        .arg(filename));
    }
    return success;
}
